name: build-test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: yarn install
      run: yarn install

    - name: Lint
      run: yarn format-check

    # - name: yarn test
    #   run: yarn test

    - name: audit packages
      run: yarn audit --audit-level=high
      if: matrix.operating-system == 'ubuntu-latest'